FROM golang:1.24-alpine

WORKDIR /app

# ดาวน์โหลด dependencies ก่อน เพื่อใช้ประโยชน์จาก Docker Cache
COPY go.mod go.sum ./
RUN go mod download

# คัดลอกโค้ดและสร้าง Binary
COPY . .
RUN go build -o main .

# กำหนด Port
EXPOSE 8080

# สั่งรัน Binary ที่สร้างเสร็จแล้ว
CMD ["./main"]